@extends('errors.layout')
@section('title', 'Access Denied')
@section('eyebrow', 'Access denied')
@section('code', '403')
@section('heading', "This one's off-limits.")
@section('message', "You don't have permission to view this page. If you think that's a mistake, reach out and we'll help you find your way.")
