@extends('errors.layout')
@section('title', 'Page Not Found')
@section('eyebrow', 'Page not found')
@section('code', '404')
@section('heading', 'This corner of downtown is empty.')
@section('message', "We couldn't find the page you were looking for. It may have moved, closed up shop, or never existed — but there's still plenty to explore.")
