@extends('errors.layout')
@section('title', 'Page Expired')
@section('eyebrow', 'Page expired')
@section('code', '419')
@section('heading', "Let's try that again.")
@section('message', 'Your session expired for security reasons. Head back and give it another go — no harm done.')
