@extends('errors.layout')
@section('title', 'Too Many Requests')
@section('eyebrow', 'Slow down')
@section('code', '429')
@section('heading', 'Whoa, easy there!')
@section('message', "You've made a few too many requests in a short time. Take a breather and try again in a moment.")
