@extends('errors.layout')
@section('title', 'Something Went Wrong')
@section('eyebrow', 'Server error')
@section('code', '500')
@section('heading', 'Well, this is embarrassing.')
@section('message', "Something went wrong on our end. We've been notified and we're looking into it — please try again in a little while.")
