@extends('errors.layout')
@section('title', 'Be Right Back')
@section('eyebrow', 'Maintenance')
@section('code', '503')
@section('heading', 'Just tidying up downtown.')
@section('message', "We're doing a little scheduled maintenance and will be back shortly. Thanks for your patience — check back in a few minutes.")
